#!/bin/bash -u
#
# Usage:
#
#  $ ANFILTE_CHANNELS="bjodah" anfilte-build /path/to/conda-recipe/ /path/to/output
#
#
if [[ -z "$ANFILTE_CACHE_DIR" ]]; then
    ANFILTE_CACHE_DIRILTE_CACHE_DIR=$(mktemp -d)
    echo "\$ANFILTE_CACHE_DIR unset, created cache dir: $ANFILTE_CACHE_DIR"
    cleanup() {
        echo "Remove cache dir \$ANFILTE_CACHE_DIR: $ANFILTE_CACHE_DIR?"
        rm -ri "$ANFILTE_CACHE_DIR"
    }
    trap cleanup INT TERM EXIT
else
    echo "Using \$ANFILTE_CACHE_DIR: $ANFILTE_CACHE_DIR"
fi
if [[ ! -d "$ANFILTE_CACHE_DIR/pkgs" ]]; then
    mkdir "$ANFILTE_CACHE_DIR/pkgs"
fi
if [[ ! -d "$ANFILTE_CACHE_DIR/conda-bld" ]]; then
    mkdir "$ANFILTE_CACHE_DIR/conda-bld"
fi

MOUNT_PATH=$(realpath $1)
REL_RECIPE_PATH=$2
DEST_PATH=$(realpath $3)

CMD="set -xe"
if [[ ${ANFILTE_CHANNELS:-""} != "" ]]; then
    for CONDA_CHANNEL in ${ANFILTE_CHANNELS:-""}; do
        ADDCHANNEL="conda config --add channels ${CONDA_CHANNEL}"
        CMD="$CMD; $ADDCHANNEL"
    done
fi
CMD="$CMD; cd /home/conda/anfilte-work; conda-build "${@:4}" --output-folder /home/conda/anfilte-out $REL_RECIPE_PATH"
set -x
CONTAINERNAME=anfilte
HOST_USER=${SUDO_USER:-${LOGNAME}}

if groups | grep docker; then
    DOCKERCMD=docker
else
    DOCKERCMD="sudo docker"
fi

set +u
${DOCKERCMD} run --name $CONTAINERNAME ${ANFILTE_DOCKER_ARGS} \
       -e HOST_USER_ID=$(id -u ${HOST_USER}) \
       -e CONDA_PKGS_DIRS="/pkgs" \
       -e CONDA_BLD_PATH="/conda-bld" \
       -v "$MOUNT_PATH":/home/conda/anfilte-work \
       -v "$DEST_PATH":/home/conda/anfilte-out \
       -v "$ANFILTE_CACHE_DIR/pkgs":/pkgs \
       -v "$ANFILTE_CACHE_DIR/conda-bld":/conda-bld \
       -it condaforge/linux-anvil-comp7 \
       bash -c "$CMD"

EXIT_CODE=$($DOCKERCMD inspect ${CONTAINERNAME} --format='{{.State.ExitCode}}')
$DOCKERCMD rm $CONTAINERNAME
exit ${EXIT_CODE}
